<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme_suggestions_alter
 */
// function custom_user_login_register_theme_suggestions_alter(array &$suggestions, array $variables)
// {
//     if(isset($variables['element']) && isset($variables['element']['#type']) && $variables['element']['#type'] == 'form')
//     {

//         $original_theme_hook = $variables['theme_hook_original'];

//         $suggestions[] = $original_theme_hook . '__' . str_replace('-', '_', $variables['element']['#id']);

//     }
// }

// /**
//  * Implements hook_form_BASE_FORM_ID_alter().
//  */
// function custom_user_login_register_form_user_login_form_alter(&$form, FormStateInterface &$form_state){

//     $form['#theme'] = ['my_user_login'];

// }

// /**
//  * Implements hook_theme()
//  */
// function custom_user_login_register_theme() {

//     $themes['my_user_login'] = [
//         'render element' => 'form'
//     ];

// }